"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'fr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.portfolio': 'Portefeuille',
    'nav.backtest': 'Backtest',
    'nav.account': 'Compte',
    'nav.platform': 'Plateforme française',
    'nav.cryptos': 'Cryptomonnaies',
    'nav.charts': 'Graphiques',
    'nav.plan': 'Plan',
    'nav.user': 'Utilisateur',
    'nav.my_profile': 'Mon Profil',
    'nav.personal_info': 'Informations personnelles',
    'nav.settings': 'Paramètres',
    'nav.account_config': 'Configuration du compte',
    'nav.security': 'Sécurité',
    'nav.password_2fa': 'Mot de passe et 2FA',
    'nav.activity': 'Activité',
    'nav.recent_actions': 'Actions récentes',
    'nav.signout': 'Se déconnecter',
    'nav.quit_session': 'Quitter la session',
    'nav.signin': 'Connexion',
    'nav.signup': 'S\'inscrire',

    // Account Page
    'account.title': 'Mon Compte',
    'account.subtitle': 'Gérez votre profil et préférences',
    'account.loading': 'Chargement de votre profil...',

    // Tabs
    'tabs.profile': 'Profil',
    'tabs.settings': 'Paramètres',
    'tabs.security': 'Sécurité',
    'tabs.activity': 'Activité',

    // Profile Section
    'profile.title': 'Informations personnelles',
    'profile.edit': 'Modifier',
    'profile.save': 'Sauvegarder',
    'profile.cancel': 'Annuler',
    'profile.plan': 'Plan',
    'profile.member_since': 'Membre depuis',
    'profile.recently': 'Récemment',

    // Contact
    'contact.title': 'Contact',
    'contact.email': 'Email principal',
    'contact.verified': 'Vérifié',
    'contact.phone': 'Téléphone',
    'contact.phone_placeholder': 'Numéro de téléphone',
    'contact.location': 'Localisation',
    'contact.location_placeholder': 'Votre localisation',
    'contact.not_provided': 'Non renseigné',

    // Stats
    'stats.title': 'Statistiques du compte',
    'stats.watchlists': 'Listes de suivis créées',
    'stats.exchanges': 'Exchanges connectés',
    'stats.cryptos': 'Cryptos suivies',
    'stats.strategies': 'Stratégies backtest créées',
    'stats.create_first': 'Créer votre première →',
    'stats.add_cryptos': 'Ajouter des cryptos →',
    'stats.coming_soon': 'Bientôt disponible',

    // Performance
    'performance.title': 'Performance récente',
    'performance.this_month': 'Ce mois',
    'performance.last_3_months': '3 derniers mois',
    'performance.this_year': 'Cette année',
    'performance.sharpe_ratio': 'Sharpe Ratio',
    'performance.max_drawdown': 'Drawdown Max',
    'performance.no_data': 'Aucune donnée de performance',
    'performance.create_backtest': 'Créez votre premier backtest !',

    // Settings
    'settings.title': 'Paramètres',
    'settings.email_notifications': 'Notifications par email',
    'settings.email_notifications_desc': 'Recevez des alertes sur vos backtests',
    'settings.dark_mode': 'Mode sombre',
    'settings.dark_mode_desc': 'Interface en thème sombre',
    'settings.language': 'Langue',
    'settings.language_desc': 'Langue de l\'interface',
    'settings.currency': 'Devise par défaut',
    'settings.currency_desc': 'Devise d\'affichage des prix',

    // Security
    'security.title': 'Sécurité',
    'security.password': 'Mot de passe',
    'security.password_changed': 'Dernière modification il y a',
    'security.password_days': 'jours',
    'security.modify': 'Modifier',
    'security.2fa': 'Authentification à deux facteurs',
    'security.2fa_desc': 'Protection supplémentaire recommandée',
    'security.coming_soon': 'Bientôt disponible',
    'security.active_sessions': 'Sessions actives',
    'security.current_session': 'Session actuelle',
    'security.active': 'Actif',
    'security.disconnect': 'Déconnecter',
    'security.api_keys': 'Clés API',
    'security.api_keys_desc': 'Gérez vos clés API pour les exchanges',
    'security.add_api_key': 'Ajouter une clé API',

    // Activity
    'activity.title': 'Activité récente',
    'activity.no_activity': 'Aucune activité récente',
    'activity.no_activity_desc': 'Vos actions apparaîtront ici',

    // Time
    'time.now': 'À l\'instant',
    'time.hours_ago': 'Il y a',
    'time.yesterday': 'Hier',

    // Common
    'common.free': 'Gratuit',

    // Home Page
    'home.hero.title1': 'Backtestez vos',
    'home.hero.title2': 'stratégies crypto',
    'home.hero.subtitle1': 'Plateforme française d\'analyse et de backtesting crypto',
    'home.hero.subtitle2': 'Testez vos stratégies sur des données historiques réelles et optimisez vos investissements',
    'home.hero.trust1': '100% Français',
    'home.hero.trust2': 'Données temps réel',
    'home.hero.trust3': 'Sécurité maximale',
    'home.hero.cta_start': 'Commencer gratuitement',
    'home.hero.cta_discover': 'Découvrir les fonctionnalités',
    'home.hero.cta_discover_mobile': 'Découvrir',
    'home.stats.backtests': 'Backtests réalisés',
    'home.stats.cryptos': 'Cryptos supportées',
    'home.stats.uptime': 'Uptime garanti',
    'home.stats.latency': 'Latence API',
    'home.features.badge': 'Fonctionnalités Premium',
    'home.features.title1': 'Outils d\'analyse',
    'home.features.title2': 'professionnels',
    'home.features.subtitle': 'Suite complète pour analyser, optimiser et gérer vos investissements crypto avec une précision institutionnelle',
    'home.features.check1': 'API temps réel',
    'home.features.check2': 'Données historiques complètes',
    'home.features.check3': 'Algorithmes propriétaires',
    'home.features.crypto.title': 'Cryptomonnaies',
    'home.features.crypto.desc': 'Suivez les cours en temps réel, analysez les tendances du marché et identifiez les opportunités d\'investissement.',
    'home.features.crypto.feat1': '500+ cryptomonnaies',
    'home.features.crypto.feat2': 'Données temps réel',
    'home.features.crypto.feat3': 'Listes personnalisées',
    'home.features.charts.title': 'Graphiques Avancés',
    'home.features.charts.desc': 'Charts professionnels avec indicateurs techniques, analyse candlestick et outils de dessin intégrés.',
    'home.features.charts.feat1': 'TradingView intégré',
    'home.features.charts.feat2': '100+ indicateurs',
    'home.features.charts.feat3': 'Outils de dessin',
    'home.features.backtest.title': 'Backtest Intelligent',
    'home.features.backtest.desc': 'Testez vos stratégies sur vos données historiques réelles. Analysez les performances passées pour optimiser l\'avenir.',
    'home.features.backtest.feat1': 'Données 5 ans',
    'home.features.backtest.feat2': 'Stratégies avancées',
    'home.features.backtest.feat3': 'Rapports détaillés',
    'home.features.portfolio.title': 'Gestion Portfolio',
    'home.features.portfolio.desc': 'Synchronisez et gérez vos portefeuilles multi-exchanges. Suivi des performances en temps réel.',
    'home.features.portfolio.feat1': 'Multi-exchanges',
    'home.features.portfolio.feat2': 'API sécurisées',
    'home.features.portfolio.feat3': 'Analytics avancés',
    'home.social.badge': 'Résultats Clients',
    'home.social.title': 'Des résultats qui parlent d\'eux-mêmes',
    'home.social.roi': 'ROI Moyen',
    'home.social.roi_period': 'Sur 12 mois',
    'home.social.volume': 'Volume Analysé',
    'home.social.volume_period': 'Par mois',
    'home.social.strategies': 'Stratégies Actives',
    'home.social.strategies_period': 'Testées quotidiennement',
    'home.social.satisfaction': 'Satisfaction',
    'home.social.satisfaction_period': 'Clients premium',
    'home.social.trader': 'Trader Indépendant',
    'home.social.testimonial1': '"Grâce aux backtests, j\'ai optimisé ma stratégie DCA et augmenté mes rendements de 180% en 8 mois."',
    'home.social.fund_manager': 'Gestionnaire de Fonds',
    'home.social.testimonial2': '"Interface pro, données fiables. Nos clients ont vu leurs portefeuilles croître de 240% cette année."',
    'home.social.investor': 'Investisseur Institutionnel',
    'home.social.testimonial3': '"Plateforme française de référence. Sécurité, performance et support technique exceptionnel."',
    'home.social.trust': 'Ils nous font confiance',
    'home.social.bank': 'Banque de France',
    'home.social.approved': 'ACPR Agréé',
    'home.social.made_france': 'Made in France',
    'home.social.soc2': 'SOC2 Type II',
    'home.tech.badge': 'Infrastructure',
    'home.tech.title1': 'Technologie de',
    'home.tech.title2': 'pointe',
    'home.tech.subtitle': 'Infrastructure haute performance conçue pour les traders professionnels et les institutions financières.',
    'home.tech.sync.title': 'Synchronisation Multi-Exchange',
    'home.tech.sync.desc': 'Connectez vos comptes Binance, Coinbase, Kraken avec des clés API sécurisées en lecture seule.',
    'home.tech.sync.check': '15+ exchanges supportés',
    'home.tech.realtime.title': 'Données Temps Réel',
    'home.tech.realtime.desc': 'Flux de données haute fréquence pour une analyse précise et des backtests fiables.',
    'home.tech.realtime.check': 'Latence < 50ms garantie',
    'home.tech.security.title': 'Sécurité Maximale',
    'home.tech.security.desc': 'Chiffrement AES-256, hébergement français, conformité RGPD. Vos données sont protégées.',
    'home.tech.security.check': 'Certifié ISO 27001',
    'home.tech.perf.title': 'Performance en Temps Réel',
    'home.tech.perf.uptime': 'Uptime',
    'home.tech.perf.latency': 'Latence',
    'home.tech.perf.monitoring': 'Monitoring',
    'home.tech.perf.live': 'LIVE',
    'home.tech.perf.encryption': 'AES Encryption',
    'home.tech.perf.secure': 'Sécurisé',
    'home.tech.stack': 'Stack Technologique',
    'home.tech.stack.typescript': 'TypeScript',
    'home.tech.stack.cloud': 'Cloud',
    'home.tech.stack.redis': 'Redis',
    'home.footer.brand_desc': 'La référence française pour le backtesting et l\'analyse de stratégies crypto. Conçu par des traders, pour des traders.',
    'home.footer.platform': 'Plateforme',
    'home.footer.dashboard': 'Tableau de bord',
    'home.footer.support': 'Support',
    'home.footer.help': 'Centre d\'aide',
    'home.footer.api_docs': 'Documentation API',
    'home.footer.tutorials': 'Tutoriels vidéo',
    'home.footer.discord': 'Communauté Discord',
    'home.footer.tech_support': 'Support technique',
    'home.footer.company': 'Entreprise',
    'home.footer.about': 'À propos',
    'home.footer.team': 'Notre équipe',
    'home.footer.careers': 'Carrières',
    'home.footer.press': 'Presse',
    'home.footer.blog': 'Blog',
    'home.footer.rgpd': 'RGPD',
    'home.footer.compliant': 'Conforme',
    'home.footer.iso': 'ISO 27001',
    'home.footer.certified': 'Certifié',
    'home.footer.french': 'Français',
    'home.footer.status': 'Status',
    'home.footer.operational': 'OPERATIONAL',
    'home.footer.copyright': 'CryptoBacktest SAS. Tous droits réservés. • Siège social: Paris, France • RCS: 123 456 789',
    'home.footer.terms': 'Conditions d\'utilisation',
    'home.footer.privacy': 'Politique de confidentialité',
    'home.footer.legal': 'Mentions légales',
    'home.footer.contact': 'Contact',

    // Backtest Page
    'backtest.badge': 'Backtest Intelligent',
    'backtest.hero.title1': 'Testez vos',
    'backtest.hero.title2': 'stratégies crypto',
    'backtest.hero.subtitle': 'Analysez les performances de vos stratégies sur des données historiques réelles',
    'backtest.hero.stat1': 'Données 5 ans',
    'backtest.hero.stat2': 'Stratégies avancées',
    'backtest.hero.stat3': 'Rapports détaillés',
    'backtest.tab.strategy': 'Backtest Strategy',
    'backtest.tab.results': 'Résultats',
    'backtest.connected_as': 'Connecté en tant que',
    'backtest.login_required': 'Connexion Requise',
    'backtest.login_message': 'Veuillez vous connecter ou créer un compte pour accéder aux fonctionnalités de backtest et sauvegarder vos stratégies personnalisées.',
    'backtest.login_info': 'Vos stratégies et données sont stockées localement dans votre navigateur pour chaque compte, garantissant la confidentialité de vos stratégies de trading.',
    'backtest.results.title': 'Résultats du Backtest',
    'backtest.results.days': 'jours',
    'backtest.results.custom_strategy': 'Stratégie Personnalisée',
    'backtest.metrics.total_roi': 'ROI Total',
    'backtest.metrics.win_rate': 'Win Rate',
    'backtest.metrics.trades': 'trades',
    'backtest.metrics.max_drawdown': 'Max Drawdown',
    'backtest.metrics.vs_hold': 'vs Buy & Hold',
    'backtest.metrics.alpha': 'Alpha',
    'backtest.comparison.title': 'Performance vs Buy & Hold',
    'backtest.comparison.your_strategy': 'Votre Stratégie:',
    'backtest.comparison.hold': 'Buy & Hold:',
    'backtest.comparison.difference': 'Différence (Alpha):',
    'backtest.stats.title': 'Statistiques de Trading',
    'backtest.stats.num_trades': 'Nombre de trades:',
    'backtest.stats.profit_factor': 'Profit Factor:',
    'backtest.stats.avg_win': 'Gain moyen:',
    'backtest.stats.avg_loss': 'Perte moyenne:',
    'backtest.stats.total_fees': 'Frais totaux:',
    'backtest.trades.title': 'Historique des Trades',
    'backtest.trades.complete': 'trades complets',
    'backtest.trades.trade': 'Trade',
    'backtest.trades.view': 'Voir le trade',
    'backtest.trades.gain': 'GAIN',
    'backtest.trades.loss': 'PERTE',
    'backtest.trades.open': 'OUVERTURE',
    'backtest.trades.close': 'FERMETURE',
    'backtest.actions.new_strategy': 'Nouvelle Stratégie',
    'backtest.actions.export': 'Exporter les Résultats',
    'backtest.no_results': 'Aucun résultat',
    'backtest.no_results_desc': 'Lancez un backtest pour voir les résultats ici.',
    'backtest.back_to_config': 'Retour à la Configuration',

    // Auth Pages
    'auth.back_home': 'Retour à l\'accueil',
    'auth.signin.title': 'Connexion',
    'auth.signin.subtitle': 'Accédez à votre plateforme CryptoBacktest',
    'auth.signin.email': 'Adresse email',
    'auth.signin.email_placeholder': 'votre@email.com',
    'auth.signin.password': 'Mot de passe',
    'auth.signin.password_placeholder': '••••••••',
    'auth.signin.forgot_password': 'Mot de passe oublié ?',
    'auth.signin.submit': 'Se connecter',
    'auth.signin.loading': 'Connexion...',
    'auth.signin.no_account': 'Pas encore de compte ?',
    'auth.signin.create_account': 'Créer un compte',
    'auth.signin.demo': 'Testez la plateforme avec votre compte',
    'auth.signin.error.fill_fields': 'Veuillez remplir tous les champs',
    'auth.signin.error.invalid_credentials': 'Email ou mot de passe incorrect',
    'auth.signin.error.unexpected': 'Une erreur inattendue s\'est produite',
    'auth.signin.success': 'Connexion réussie ! Redirection...',
    'auth.signup.title': 'Créer un compte',
    'auth.signup.subtitle': 'Rejoignez la plateforme CryptoBacktest',
    'auth.signup.confirm_password': 'Confirmer le mot de passe',
    'auth.signup.password_hint': 'Au moins 6 caractères',
    'auth.signup.terms1': 'J\'accepte les',
    'auth.signup.terms2': 'conditions d\'utilisation',
    'auth.signup.terms3': 'et la',
    'auth.signup.terms4': 'politique de confidentialité',
    'auth.signup.submit': 'Créer mon compte',
    'auth.signup.loading': 'Création...',
    'auth.signup.have_account': 'Déjà un compte ?',
    'auth.signup.signin': 'Se connecter',
    'auth.signup.features.title': 'Votre compte inclut :',
    'auth.signup.features.sync': 'Synchronisation de portefeuille',
    'auth.signup.features.backtest': 'Backtests illimités (plan gratuit)',
    'auth.signup.features.analysis': 'Analyses et graphiques temps réel',
    'auth.signup.error.fill_fields': 'Veuillez remplir tous les champs',
    'auth.signup.error.password_mismatch': 'Les mots de passe ne correspondent pas',
    'auth.signup.error.password_length': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.signup.success': 'Compte créé avec succès ! Vous allez être connecté automatiquement...',

    // Backtest Configuration
    'backtest.config.title': 'Configuration du Backtest',
    'backtest.config.subtitle': 'Configurez votre stratégie de trading et testez-la sur des données historiques pour évaluer ses performances et optimiser vos paramètres.',
    'backtest.config.base_params': 'Paramètres de Base',
    'backtest.config.cryptocurrency': 'Cryptomonnaie',
    'backtest.config.test_period': 'Période de Test',
    'backtest.config.initial_capital': 'Capital Initial ($)',
    'backtest.config.position_size': 'Taille de Position (% du capital)',
    'backtest.config.trading_strategy': 'Stratégie de Trading',
    'backtest.config.recommended_strategies': '🎯 Stratégies Recommandées',
    'backtest.config.custom_strategy': '🔧 Stratégie Personnalisée',
    'backtest.config.strategy_params': 'Paramètres de',
    'backtest.config.risk_management': 'Gestion des Risques',
    'backtest.config.stop_loss': 'Stop Loss (%)',
    'backtest.config.take_profit': 'Take Profit (%)',
    'backtest.config.summary': 'Résumé',
    'backtest.config.crypto': 'Crypto:',
    'backtest.config.period': 'Période:',
    'backtest.config.strategy': 'Stratégie:',
    'backtest.config.capital': 'Capital:',
    'backtest.config.position': 'Position:',
    'backtest.config.save': 'Sauvegarder',
    'backtest.config.load': 'Charger',
    'backtest.config.start': 'Lancer le Backtest',
    'backtest.config.running': 'Calcul en cours...',
    'backtest.config.tip': '💡 Astuce:',
    'backtest.config.tip_text': 'Commencez avec des périodes courtes (1-3 mois) pour tester rapidement vos stratégies avant d\'analyser des périodes plus longues.',

    // Periods
    'period.1_month': '1 Mois',
    'period.1_month_desc': 'Test rapide',
    'period.3_months': '3 Mois',
    'period.3_months_desc': 'Cycle court',
    'period.6_months': '6 Mois',
    'period.6_months_desc': 'Cycle moyen',
    'period.1_year': '1 An',
    'period.1_year_desc': 'Cycle complet',
    'period.2_years': '2 Ans',
    'period.2_years_desc': 'Long terme',
    'period.5_years': '5 Ans',
    'period.5_years_desc': 'Très long terme',

    // Recommended Strategies
    'strategy.rsi.name': 'RSI Oversold/Overbought',
    'strategy.rsi.desc': 'Achat quand RSI < 30, vente quand RSI > 70',
    'strategy.rsi.type': 'Oscillateur',
    'strategy.ema.name': 'EMA Crossover',
    'strategy.ema.desc': 'Signal de croisement entre EMA rapide et EMA lente',
    'strategy.ema.type': 'Trend Following',
    'strategy.bollinger.name': 'Bollinger Bands Mean Reversion',
    'strategy.bollinger.desc': 'Achat sur bande basse, vente sur bande haute',
    'strategy.bollinger.type': 'Mean Reversion',
    'strategy.macd_rsi.name': 'MACD + RSI Combo',
    'strategy.macd_rsi.desc': 'MACD pour la tendance + RSI pour le timing',
    'strategy.macd_rsi.type': 'Multi-Indicateur',
    'strategy.triple_ema.name': 'Triple EMA Strategy',
    'strategy.triple_ema.desc': 'EMA 9, 21, 55 pour confirmation multiple',
    'strategy.triple_ema.type': 'Trend Following',
    'strategy.stoch_bollinger.name': 'Stochastic + Bollinger',
    'strategy.stoch_bollinger.desc': 'Stochastic pour momentum + Bollinger pour niveaux',
    'strategy.stoch_bollinger.type': 'Multi-Indicateur',

    // Difficulty levels
    'difficulty.beginner': 'Débutant',
    'difficulty.intermediate': 'Intermédiaire',
    'difficulty.advanced': 'Avancé',

    // Indicators
    'indicator.select_indicators': '🔧 Sélectionnez vos Indicateurs',
    'indicator.config_indicators': '⚙️ Configuration des Indicateurs',
    'indicator.combination_logic': '🧮 Logique de Combinaison',
    'indicator.entry_logic': 'Logique d\'entrée',
    'indicator.exit_logic': 'Logique de sortie',
    'indicator.all_and': 'TOUS les indicateurs (ET)',
    'indicator.any_or': 'AU MOINS UN indicateur (OU)',
    'indicator.all_must_match': 'Toutes les conditions doivent être remplies',
    'indicator.one_must_match': 'Au moins une condition doit être remplie',
    'indicator.parameters': 'Paramètres',
    'indicator.entry_conditions': 'Conditions d\'Entrée',
    'indicator.exit_conditions': 'Conditions de Sortie',
    'indicator.remove': 'Supprimer',

    // Indicator categories
    'indicator.category.oscillator': 'Oscillateur',
    'indicator.category.trend': 'Tendance',
    'indicator.category.momentum': 'Momentum',
    'indicator.category.volatility': 'Volatilité',
    'indicator.category.volume': 'Volume',
    'indicator.category.support_resistance': 'Support/Résistance',

    // Indicator parameters
    'indicator.param.period': 'Période',
    'indicator.param.fast_period': 'Période Rapide',
    'indicator.param.slow_period': 'Période Lente',
    'indicator.param.signal_period': 'Période Signal',
    'indicator.param.std_dev': 'Déviation Standard',
    'indicator.param.k_period': 'Période %K',
    'indicator.param.d_period': 'Période %D',
    'indicator.param.rsi_period': 'Période RSI',
    'indicator.param.rsi_oversold': 'RSI Survente',
    'indicator.param.rsi_overbought': 'RSI Surachat',
    'indicator.param.ema_fast': 'EMA Rapide',
    'indicator.param.ema_slow': 'EMA Lente',
    'indicator.param.bollinger_period': 'Période',
    'indicator.param.bollinger_std_dev': 'Déviation Standard',

    // Strategy summary
    'strategy.summary.title': '✅ Votre Stratégie Personnalisée',
    'strategy.summary.custom': 'Stratégie Personnalisée',
    'strategy.summary.indicators': 'indicateur(s)',
    'strategy.summary.entry': 'Entrée:',
    'strategy.summary.exit': 'Sortie:',
    'strategy.summary.params': 'Paramètres:',

    // Save/Load modals
    'modal.save.title': 'Sauvegarder la Stratégie',
    'modal.save.name': 'Nom de la stratégie *',
    'modal.save.name_placeholder': 'Ex: Ma stratégie RSI-EMA',
    'modal.save.description': 'Description (optionnel)',
    'modal.save.description_placeholder': 'Description de la stratégie...',
    'modal.save.cancel': 'Annuler',
    'modal.save.confirm': 'Sauvegarder',
    'modal.load.title': 'Charger une Stratégie Sauvegardée',
    'modal.load.no_strategies': 'Aucune stratégie sauvegardée',
    'modal.load.created': 'Créée:',
    'modal.load.indicators': 'Indicateurs:',
    'modal.load.load_button': 'Charger',
    'modal.load.delete_button': '✕',
    'modal.load.close': 'Fermer',
    'modal.load.delete_confirm': 'Êtes-vous sûr de vouloir supprimer cette stratégie ?',

    // Cryptos Page
    'cryptos.my_watchlists': 'Mes Listes de Suivi',
    'cryptos.market_global': 'Marché Global',
    'cryptos.my_lists': 'Mes Listes',
    'cryptos.market_cap_global': 'Market Cap Global',
    'cryptos.volume_24h': 'Volume 24h',
    'cryptos.dominance_btc': 'Dominance BTC',
    'cryptos.dominance_eth': 'Dominance ETH',
    'cryptos.top_performers': 'Top Performers 24h',
    'cryptos.top_declines': 'Top Declins 24h',
    'cryptos.search_placeholder': 'Rechercher par nom, symbole, ID ou tag...',
    'cryptos.price': 'Prix',
    'cryptos.market_cap': 'Capitalisation',
    'cryptos.volume': 'Volume',
    'cryptos.rank': 'Rang',
    'cryptos.variation': 'Variation',
    'cryptos.price_and_hl': 'Prix & H/L',
    'cryptos.delete_list': 'Supprimer cette liste',
    'cryptos.total_markets': 'Total des marchés',
    'cryptos.global_trading': 'Trading global',
    'cryptos.market_share': 'Part de marché',
    'cryptos.connection_required': 'Connexion requise pour accéder aux listes personnalisées',
    'cryptos.your_custom_lists': 'Vos listes de suivi personnalisées',
    'cryptos.create_first_list': 'Commencez par créer votre première liste de suivi ou ajoutez des cryptos depuis l\'onglet Marché.',
    'cryptos.create_watchlist': 'Créer une Liste',
    'cryptos.tip': '💡 Astuce : Cliquez sur ⭐ dans l\'onglet Marché pour ajouter des cryptos',
    'cryptos.no_lists': 'Aucune liste pour le moment',

    // Portfolio Page
    'portfolio.title': 'Mon Portefeuille',
    'portfolio.subtitle': 'Gérez et suivez vos investissements crypto',
    'portfolio.manual_portfolio': 'Portfolio Manuel',
    'portfolio.exchange_portfolio': 'Synchronisation Exchange',
    'portfolio.add': 'Ajouter',
    'portfolio.current_price': 'Prix Actuel',
    'portfolio.avg_price': 'Prix Moyen',
    'portfolio.weighted_avg_price': 'Prix moyen pondéré',
    'portfolio.add_transaction': 'Ajouter une transaction',
    'portfolio.add_first_crypto': 'Ajouter ma première crypto',
    'portfolio.modify': 'Modifier',
    'portfolio.delete': 'Supprimer',
    'portfolio.modify_transaction': 'Modifier Transaction',
    'portfolio.delete_transaction_confirm': 'Supprimer cette transaction ?',
    'portfolio.delete_transaction': 'Supprimer cette transaction',
    'portfolio.purchase_price': 'Prix d\'achat ($)',
    'portfolio.add_position': 'Ajouter une position',
    'portfolio.modify_position': 'Modifier une position',
    'portfolio.search_crypto': 'Rechercher une crypto...',
    'portfolio.loading_price': 'Prix en cours...',
    'portfolio.avg_purchase_price': 'Prix moyen d\'achat ($)',
    'portfolio.current_price_label': 'Prix actuel :',
    'portfolio.add_exchange': 'Ajouter un Exchange',
    'portfolio.quantity': 'Quantité',
    'portfolio.value': 'Valeur',
    'portfolio.profit_loss': 'P&L',
    'portfolio.total_value': 'Valeur Totale',
    'portfolio.total_invested': 'Investi Total',
    'portfolio.total_profit': 'Profit/Perte Total',
    'portfolio.best_performer': 'Meilleure Performance',
    'portfolio.worst_performer': 'Pire Performance',
    'portfolio.crypto': 'Crypto',
    'portfolio.actions': 'Actions',
    'portfolio.empty_state': 'Aucune crypto dans votre portefeuille',
    'portfolio.empty_desc': 'Commencez par ajouter vos premières positions',
    'portfolio.refresh': 'Actualiser les prix',
    'portfolio.show_values': 'Afficher les valeurs',
    'portfolio.hide_values': 'Masquer les valeurs',
    'portfolio.transaction_date': 'Date',
    'portfolio.transaction_type': 'Type',
    'portfolio.transaction_buy': 'Achat',
    'portfolio.transaction_sell': 'Vente',
    'portfolio.no_transactions': 'Aucune transaction',
    'portfolio.view_transactions': 'Voir les transactions',
    'portfolio.close': 'Fermer',
    'portfolio.save': 'Sauvegarder',
    'portfolio.cancel': 'Annuler',

    // Charts Page
    'charts.title': 'Graphiques Avancés',
    'charts.subtitle': 'Analysez les marchés avec des outils professionnels',
    'charts.search_crypto': 'Rechercher une cryptomonnaie',
    'charts.my_watchlists': 'Mes Listes de Suivi',
    'charts.add_to_portfolio': 'Ajouter au Portefeuille',
    'charts.refresh': 'Actualiser',
    'charts.fullscreen': 'Plein écran',
    'charts.download': 'Télécharger',
    'charts.crypto_info': 'Informations Crypto',
    'charts.current_price': 'Prix Actuel',
    'charts.change_24h': 'Variation 24h',
    'charts.market_cap': 'Market Cap',
    'charts.volume_24h': 'Volume 24h',
    'charts.loading': 'Chargement du graphique...',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.portfolio': 'Portfolio',
    'nav.backtest': 'Backtest',
    'nav.account': 'Account',
    'nav.platform': 'French platform',
    'nav.cryptos': 'Cryptocurrencies',
    'nav.charts': 'Charts',
    'nav.plan': 'Plan',
    'nav.user': 'User',
    'nav.my_profile': 'My Profile',
    'nav.personal_info': 'Personal information',
    'nav.settings': 'Settings',
    'nav.account_config': 'Account configuration',
    'nav.security': 'Security',
    'nav.password_2fa': 'Password and 2FA',
    'nav.activity': 'Activity',
    'nav.recent_actions': 'Recent actions',
    'nav.signout': 'Sign out',
    'nav.quit_session': 'Quit session',
    'nav.signin': 'Sign in',
    'nav.signup': 'Sign up',

    // Account Page
    'account.title': 'My Account',
    'account.subtitle': 'Manage your profile and preferences',
    'account.loading': 'Loading your profile...',

    // Tabs
    'tabs.profile': 'Profile',
    'tabs.settings': 'Settings',
    'tabs.security': 'Security',
    'tabs.activity': 'Activity',

    // Profile Section
    'profile.title': 'Personal Information',
    'profile.edit': 'Edit',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.plan': 'Plan',
    'profile.member_since': 'Member since',
    'profile.recently': 'Recently',

    // Contact
    'contact.title': 'Contact',
    'contact.email': 'Primary email',
    'contact.verified': 'Verified',
    'contact.phone': 'Phone',
    'contact.phone_placeholder': 'Phone number',
    'contact.location': 'Location',
    'contact.location_placeholder': 'Your location',
    'contact.not_provided': 'Not provided',

    // Stats
    'stats.title': 'Account Statistics',
    'stats.watchlists': 'Watchlists created',
    'stats.exchanges': 'Connected exchanges',
    'stats.cryptos': 'Followed cryptos',
    'stats.strategies': 'Backtest strategies created',
    'stats.create_first': 'Create your first →',
    'stats.add_cryptos': 'Add cryptos →',
    'stats.coming_soon': 'Coming soon',

    // Performance
    'performance.title': 'Recent Performance',
    'performance.this_month': 'This month',
    'performance.last_3_months': 'Last 3 months',
    'performance.this_year': 'This year',
    'performance.sharpe_ratio': 'Sharpe Ratio',
    'performance.max_drawdown': 'Max Drawdown',
    'performance.no_data': 'No performance data',
    'performance.create_backtest': 'Create your first backtest!',

    // Settings
    'settings.title': 'Settings',
    'settings.email_notifications': 'Email notifications',
    'settings.email_notifications_desc': 'Receive alerts about your backtests',
    'settings.dark_mode': 'Dark mode',
    'settings.dark_mode_desc': 'Dark theme interface',
    'settings.language': 'Language',
    'settings.language_desc': 'Interface language',
    'settings.currency': 'Default currency',
    'settings.currency_desc': 'Price display currency',

    // Security
    'security.title': 'Security',
    'security.password': 'Password',
    'security.password_changed': 'Last modified',
    'security.password_days': 'days ago',
    'security.modify': 'Modify',
    'security.2fa': 'Two-factor authentication',
    'security.2fa_desc': 'Additional protection recommended',
    'security.coming_soon': 'Coming soon',
    'security.active_sessions': 'Active sessions',
    'security.current_session': 'Current session',
    'security.active': 'Active',
    'security.disconnect': 'Disconnect',
    'security.api_keys': 'API Keys',
    'security.api_keys_desc': 'Manage your exchange API keys',
    'security.add_api_key': 'Add API key',

    // Activity
    'activity.title': 'Recent Activity',
    'activity.no_activity': 'No recent activity',
    'activity.no_activity_desc': 'Your actions will appear here',

    // Time
    'time.now': 'Just now',
    'time.hours_ago': '',
    'time.yesterday': 'Yesterday',

    // Common
    'common.free': 'Free',

    // Home Page
    'home.hero.title1': 'Backtest your',
    'home.hero.title2': 'crypto strategies',
    'home.hero.subtitle1': 'French crypto analysis and backtesting platform',
    'home.hero.subtitle2': 'Test your strategies on real historical data and optimize your investments',
    'home.hero.trust1': '100% French',
    'home.hero.trust2': 'Real-time data',
    'home.hero.trust3': 'Maximum security',
    'home.hero.cta_start': 'Start for free',
    'home.hero.cta_discover': 'Discover features',
    'home.hero.cta_discover_mobile': 'Discover',
    'home.stats.backtests': 'Backtests performed',
    'home.stats.cryptos': 'Supported cryptos',
    'home.stats.uptime': 'Guaranteed uptime',
    'home.stats.latency': 'API latency',
    'home.features.badge': 'Premium Features',
    'home.features.title1': 'Professional',
    'home.features.title2': 'analysis tools',
    'home.features.subtitle': 'Complete suite to analyze, optimize and manage your crypto investments with institutional precision',
    'home.features.check1': 'Real-time API',
    'home.features.check2': 'Complete historical data',
    'home.features.check3': 'Proprietary algorithms',
    'home.features.crypto.title': 'Cryptocurrencies',
    'home.features.crypto.desc': 'Track prices in real-time, analyze market trends and identify investment opportunities.',
    'home.features.crypto.feat1': '500+ cryptocurrencies',
    'home.features.crypto.feat2': 'Real-time data',
    'home.features.crypto.feat3': 'Custom watchlists',
    'home.features.charts.title': 'Advanced Charts',
    'home.features.charts.desc': 'Professional charts with technical indicators, candlestick analysis and integrated drawing tools.',
    'home.features.charts.feat1': 'TradingView integrated',
    'home.features.charts.feat2': '100+ indicators',
    'home.features.charts.feat3': 'Drawing tools',
    'home.features.backtest.title': 'Smart Backtest',
    'home.features.backtest.desc': 'Test your strategies on real historical data. Analyze past performance to optimize the future.',
    'home.features.backtest.feat1': '5 years data',
    'home.features.backtest.feat2': 'Advanced strategies',
    'home.features.backtest.feat3': 'Detailed reports',
    'home.features.portfolio.title': 'Portfolio Management',
    'home.features.portfolio.desc': 'Synchronize and manage your multi-exchange portfolios. Real-time performance tracking.',
    'home.features.portfolio.feat1': 'Multi-exchanges',
    'home.features.portfolio.feat2': 'Secure APIs',
    'home.features.portfolio.feat3': 'Advanced analytics',
    'home.social.badge': 'Client Results',
    'home.social.title': 'Results that speak for themselves',
    'home.social.roi': 'Average ROI',
    'home.social.roi_period': 'Over 12 months',
    'home.social.volume': 'Volume Analyzed',
    'home.social.volume_period': 'Per month',
    'home.social.strategies': 'Active Strategies',
    'home.social.strategies_period': 'Tested daily',
    'home.social.satisfaction': 'Satisfaction',
    'home.social.satisfaction_period': 'Premium clients',
    'home.social.trader': 'Independent Trader',
    'home.social.testimonial1': '"Thanks to backtests, I optimized my DCA strategy and increased my returns by 180% in 8 months."',
    'home.social.fund_manager': 'Fund Manager',
    'home.social.testimonial2': '"Professional interface, reliable data. Our clients have seen their portfolios grow by 240% this year."',
    'home.social.investor': 'Institutional Investor',
    'home.social.testimonial3': '"French reference platform. Security, performance and exceptional technical support."',
    'home.social.trust': 'They trust us',
    'home.social.bank': 'Bank of France',
    'home.social.approved': 'ACPR Approved',
    'home.social.made_france': 'Made in France',
    'home.social.soc2': 'SOC2 Type II',
    'home.tech.badge': 'Infrastructure',
    'home.tech.title1': 'Cutting-edge',
    'home.tech.title2': 'technology',
    'home.tech.subtitle': 'High-performance infrastructure designed for professional traders and financial institutions.',
    'home.tech.sync.title': 'Multi-Exchange Sync',
    'home.tech.sync.desc': 'Connect your Binance, Coinbase, Kraken accounts with secure read-only API keys.',
    'home.tech.sync.check': '15+ supported exchanges',
    'home.tech.realtime.title': 'Real-Time Data',
    'home.tech.realtime.desc': 'High-frequency data feeds for accurate analysis and reliable backtests.',
    'home.tech.realtime.check': 'Guaranteed < 50ms latency',
    'home.tech.security.title': 'Maximum Security',
    'home.tech.security.desc': 'AES-256 encryption, French hosting, GDPR compliance. Your data is protected.',
    'home.tech.security.check': 'ISO 27001 certified',
    'home.tech.perf.title': 'Real-Time Performance',
    'home.tech.perf.uptime': 'Uptime',
    'home.tech.perf.latency': 'Latency',
    'home.tech.perf.monitoring': 'Monitoring',
    'home.tech.perf.live': 'LIVE',
    'home.tech.perf.encryption': 'AES Encryption',
    'home.tech.perf.secure': 'Secure',
    'home.tech.stack': 'Tech Stack',
    'home.tech.stack.typescript': 'TypeScript',
    'home.tech.stack.cloud': 'Cloud',
    'home.tech.stack.redis': 'Redis',
    'home.footer.brand_desc': 'The French reference for crypto strategy backtesting and analysis. Designed by traders, for traders.',
    'home.footer.platform': 'Platform',
    'home.footer.dashboard': 'Dashboard',
    'home.footer.support': 'Support',
    'home.footer.help': 'Help Center',
    'home.footer.api_docs': 'API Documentation',
    'home.footer.tutorials': 'Video tutorials',
    'home.footer.discord': 'Discord Community',
    'home.footer.tech_support': 'Technical support',
    'home.footer.company': 'Company',
    'home.footer.about': 'About',
    'home.footer.team': 'Our team',
    'home.footer.careers': 'Careers',
    'home.footer.press': 'Press',
    'home.footer.blog': 'Blog',
    'home.footer.rgpd': 'GDPR',
    'home.footer.compliant': 'Compliant',
    'home.footer.iso': 'ISO 27001',
    'home.footer.certified': 'Certified',
    'home.footer.french': 'French',
    'home.footer.status': 'Status',
    'home.footer.operational': 'OPERATIONAL',
    'home.footer.copyright': 'CryptoBacktest SAS. All rights reserved. • Headquarters: Paris, France • RCS: 123 456 789',
    'home.footer.terms': 'Terms of use',
    'home.footer.privacy': 'Privacy policy',
    'home.footer.legal': 'Legal notice',
    'home.footer.contact': 'Contact',

    // Backtest Page
    'backtest.badge': 'Smart Backtest',
    'backtest.hero.title1': 'Test your',
    'backtest.hero.title2': 'crypto strategies',
    'backtest.hero.subtitle': 'Analyze your strategies performance on real historical data',
    'backtest.hero.stat1': '5 years data',
    'backtest.hero.stat2': 'Advanced strategies',
    'backtest.hero.stat3': 'Detailed reports',
    'backtest.tab.strategy': 'Backtest Strategy',
    'backtest.tab.results': 'Results',
    'backtest.connected_as': 'Connected as',
    'backtest.login_required': 'Login Required',
    'backtest.login_message': 'Please sign in or create an account to access backtest features and save your custom strategies.',
    'backtest.login_info': 'Your strategies and data are stored locally in your browser for each account, ensuring the confidentiality of your trading strategies.',
    'backtest.results.title': 'Backtest Results',
    'backtest.results.days': 'days',
    'backtest.results.custom_strategy': 'Custom Strategy',
    'backtest.metrics.total_roi': 'Total ROI',
    'backtest.metrics.win_rate': 'Win Rate',
    'backtest.metrics.trades': 'trades',
    'backtest.metrics.max_drawdown': 'Max Drawdown',
    'backtest.metrics.vs_hold': 'vs Buy & Hold',
    'backtest.metrics.alpha': 'Alpha',
    'backtest.comparison.title': 'Performance vs Buy & Hold',
    'backtest.comparison.your_strategy': 'Your Strategy:',
    'backtest.comparison.hold': 'Buy & Hold:',
    'backtest.comparison.difference': 'Difference (Alpha):',
    'backtest.stats.title': 'Trading Statistics',
    'backtest.stats.num_trades': 'Number of trades:',
    'backtest.stats.profit_factor': 'Profit Factor:',
    'backtest.stats.avg_win': 'Average win:',
    'backtest.stats.avg_loss': 'Average loss:',
    'backtest.stats.total_fees': 'Total fees:',
    'backtest.trades.title': 'Trade History',
    'backtest.trades.complete': 'complete trades',
    'backtest.trades.trade': 'Trade',
    'backtest.trades.view': 'View trade',
    'backtest.trades.gain': 'GAIN',
    'backtest.trades.loss': 'LOSS',
    'backtest.trades.open': 'OPEN',
    'backtest.trades.close': 'CLOSE',
    'backtest.actions.new_strategy': 'New Strategy',
    'backtest.actions.export': 'Export Results',
    'backtest.no_results': 'No results',
    'backtest.no_results_desc': 'Run a backtest to see results here.',
    'backtest.back_to_config': 'Back to Configuration',

    // Auth Pages
    'auth.back_home': 'Back to home',
    'auth.signin.title': 'Sign in',
    'auth.signin.subtitle': 'Access your CryptoBacktest platform',
    'auth.signin.email': 'Email address',
    'auth.signin.email_placeholder': 'your@email.com',
    'auth.signin.password': 'Password',
    'auth.signin.password_placeholder': '••••••••',
    'auth.signin.forgot_password': 'Forgot password?',
    'auth.signin.submit': 'Sign in',
    'auth.signin.loading': 'Signing in...',
    'auth.signin.no_account': 'Don\'t have an account?',
    'auth.signin.create_account': 'Create account',
    'auth.signin.demo': 'Test the platform with your account',
    'auth.signin.error.fill_fields': 'Please fill in all fields',
    'auth.signin.error.invalid_credentials': 'Invalid email or password',
    'auth.signin.error.unexpected': 'An unexpected error occurred',
    'auth.signin.success': 'Login successful! Redirecting...',
    'auth.signup.title': 'Create account',
    'auth.signup.subtitle': 'Join the CryptoBacktest platform',
    'auth.signup.confirm_password': 'Confirm password',
    'auth.signup.password_hint': 'At least 6 characters',
    'auth.signup.terms1': 'I accept the',
    'auth.signup.terms2': 'terms of use',
    'auth.signup.terms3': 'and the',
    'auth.signup.terms4': 'privacy policy',
    'auth.signup.submit': 'Create my account',
    'auth.signup.loading': 'Creating...',
    'auth.signup.have_account': 'Already have an account?',
    'auth.signup.signin': 'Sign in',
    'auth.signup.features.title': 'Your account includes:',
    'auth.signup.features.sync': 'Portfolio synchronization',
    'auth.signup.features.backtest': 'Unlimited backtests (free plan)',
    'auth.signup.features.analysis': 'Real-time analysis and charts',
    'auth.signup.error.fill_fields': 'Please fill in all fields',
    'auth.signup.error.password_mismatch': 'Passwords do not match',
    'auth.signup.error.password_length': 'Password must be at least 6 characters',
    'auth.signup.success': 'Account created successfully! You will be logged in automatically...',

    // Backtest Configuration
    'backtest.config.title': 'Backtest Configuration',
    'backtest.config.subtitle': 'Configure your trading strategy and test it on historical data to evaluate its performance and optimize your parameters.',
    'backtest.config.base_params': 'Base Parameters',
    'backtest.config.cryptocurrency': 'Cryptocurrency',
    'backtest.config.test_period': 'Test Period',
    'backtest.config.initial_capital': 'Initial Capital ($)',
    'backtest.config.position_size': 'Position Size (% of capital)',
    'backtest.config.trading_strategy': 'Trading Strategy',
    'backtest.config.recommended_strategies': '🎯 Recommended Strategies',
    'backtest.config.custom_strategy': '🔧 Custom Strategy',
    'backtest.config.strategy_params': 'Parameters for',
    'backtest.config.risk_management': 'Risk Management',
    'backtest.config.stop_loss': 'Stop Loss (%)',
    'backtest.config.take_profit': 'Take Profit (%)',
    'backtest.config.summary': 'Summary',
    'backtest.config.crypto': 'Crypto:',
    'backtest.config.period': 'Period:',
    'backtest.config.strategy': 'Strategy:',
    'backtest.config.capital': 'Capital:',
    'backtest.config.position': 'Position:',
    'backtest.config.save': 'Save',
    'backtest.config.load': 'Load',
    'backtest.config.start': 'Start Backtest',
    'backtest.config.running': 'Calculating...',
    'backtest.config.tip': '💡 Tip:',
    'backtest.config.tip_text': 'Start with short periods (1-3 months) to quickly test your strategies before analyzing longer periods.',

    // Periods
    'period.1_month': '1 Month',
    'period.1_month_desc': 'Quick test',
    'period.3_months': '3 Months',
    'period.3_months_desc': 'Short cycle',
    'period.6_months': '6 Months',
    'period.6_months_desc': 'Medium cycle',
    'period.1_year': '1 Year',
    'period.1_year_desc': 'Full cycle',
    'period.2_years': '2 Years',
    'period.2_years_desc': 'Long term',
    'period.5_years': '5 Years',
    'period.5_years_desc': 'Very long term',

    // Recommended Strategies
    'strategy.rsi.name': 'RSI Oversold/Overbought',
    'strategy.rsi.desc': 'Buy when RSI < 30, sell when RSI > 70',
    'strategy.rsi.type': 'Oscillator',
    'strategy.ema.name': 'EMA Crossover',
    'strategy.ema.desc': 'Crossover signal between fast and slow EMA',
    'strategy.ema.type': 'Trend Following',
    'strategy.bollinger.name': 'Bollinger Bands Mean Reversion',
    'strategy.bollinger.desc': 'Buy at lower band, sell at upper band',
    'strategy.bollinger.type': 'Mean Reversion',
    'strategy.macd_rsi.name': 'MACD + RSI Combo',
    'strategy.macd_rsi.desc': 'MACD for trend + RSI for timing',
    'strategy.macd_rsi.type': 'Multi-Indicator',
    'strategy.triple_ema.name': 'Triple EMA Strategy',
    'strategy.triple_ema.desc': 'EMA 9, 21, 55 for multiple confirmation',
    'strategy.triple_ema.type': 'Trend Following',
    'strategy.stoch_bollinger.name': 'Stochastic + Bollinger',
    'strategy.stoch_bollinger.desc': 'Stochastic for momentum + Bollinger for levels',
    'strategy.stoch_bollinger.type': 'Multi-Indicator',

    // Difficulty levels
    'difficulty.beginner': 'Beginner',
    'difficulty.intermediate': 'Intermediate',
    'difficulty.advanced': 'Advanced',

    // Indicators
    'indicator.select_indicators': '🔧 Select Your Indicators',
    'indicator.config_indicators': '⚙️ Indicator Configuration',
    'indicator.combination_logic': '🧮 Combination Logic',
    'indicator.entry_logic': 'Entry logic',
    'indicator.exit_logic': 'Exit logic',
    'indicator.all_and': 'ALL indicators (AND)',
    'indicator.any_or': 'AT LEAST ONE indicator (OR)',
    'indicator.all_must_match': 'All conditions must be met',
    'indicator.one_must_match': 'At least one condition must be met',
    'indicator.parameters': 'Parameters',
    'indicator.entry_conditions': 'Entry Conditions',
    'indicator.exit_conditions': 'Exit Conditions',
    'indicator.remove': 'Remove',

    // Indicator categories
    'indicator.category.oscillator': 'Oscillator',
    'indicator.category.trend': 'Trend',
    'indicator.category.momentum': 'Momentum',
    'indicator.category.volatility': 'Volatility',
    'indicator.category.volume': 'Volume',
    'indicator.category.support_resistance': 'Support/Resistance',

    // Indicator parameters
    'indicator.param.period': 'Period',
    'indicator.param.fast_period': 'Fast Period',
    'indicator.param.slow_period': 'Slow Period',
    'indicator.param.signal_period': 'Signal Period',
    'indicator.param.std_dev': 'Standard Deviation',
    'indicator.param.k_period': '%K Period',
    'indicator.param.d_period': '%D Period',
    'indicator.param.rsi_period': 'RSI Period',
    'indicator.param.rsi_oversold': 'RSI Oversold',
    'indicator.param.rsi_overbought': 'RSI Overbought',
    'indicator.param.ema_fast': 'Fast EMA',
    'indicator.param.ema_slow': 'Slow EMA',
    'indicator.param.bollinger_period': 'Period',
    'indicator.param.bollinger_std_dev': 'Standard Deviation',

    // Strategy summary
    'strategy.summary.title': '✅ Your Custom Strategy',
    'strategy.summary.custom': 'Custom Strategy',
    'strategy.summary.indicators': 'indicator(s)',
    'strategy.summary.entry': 'Entry:',
    'strategy.summary.exit': 'Exit:',
    'strategy.summary.params': 'Parameters:',

    // Save/Load modals
    'modal.save.title': 'Save Strategy',
    'modal.save.name': 'Strategy name *',
    'modal.save.name_placeholder': 'Ex: My RSI-EMA strategy',
    'modal.save.description': 'Description (optional)',
    'modal.save.description_placeholder': 'Strategy description...',
    'modal.save.cancel': 'Cancel',
    'modal.save.confirm': 'Save',
    'modal.load.title': 'Load Saved Strategy',
    'modal.load.no_strategies': 'No saved strategies',
    'modal.load.created': 'Created:',
    'modal.load.indicators': 'Indicators:',
    'modal.load.load_button': 'Load',
    'modal.load.delete_button': '✕',
    'modal.load.close': 'Close',
    'modal.load.delete_confirm': 'Are you sure you want to delete this strategy?',

    // Cryptos Page
    'cryptos.my_watchlists': 'My Watchlists',
    'cryptos.market_global': 'Global Market',
    'cryptos.my_lists': 'My Lists',
    'cryptos.market_cap_global': 'Global Market Cap',
    'cryptos.volume_24h': '24h Volume',
    'cryptos.dominance_btc': 'BTC Dominance',
    'cryptos.dominance_eth': 'ETH Dominance',
    'cryptos.top_performers': 'Top Performers 24h',
    'cryptos.top_declines': 'Top Decliners 24h',
    'cryptos.search_placeholder': 'Search by name, symbol, ID or tag...',
    'cryptos.price': 'Price',
    'cryptos.market_cap': 'Market Cap',
    'cryptos.volume': 'Volume',
    'cryptos.rank': 'Rank',
    'cryptos.variation': 'Change',
    'cryptos.price_and_hl': 'Price & H/L',
    'cryptos.delete_list': 'Delete this list',
    'cryptos.total_markets': 'Total markets',
    'cryptos.global_trading': 'Global trading',
    'cryptos.market_share': 'Market share',
    'cryptos.connection_required': 'Login required to access custom lists',
    'cryptos.your_custom_lists': 'Your custom watchlists',
    'cryptos.create_first_list': 'Start by creating your first watchlist or add cryptos from the Market tab.',
    'cryptos.create_watchlist': 'Create List',
    'cryptos.tip': '💡 Tip: Click ⭐ in the Market tab to add cryptos',
    'cryptos.no_lists': 'No lists yet',

    // Portfolio Page
    'portfolio.title': 'My Portfolio',
    'portfolio.subtitle': 'Manage and track your crypto investments',
    'portfolio.manual_portfolio': 'Manual Portfolio',
    'portfolio.exchange_portfolio': 'Exchange Sync',
    'portfolio.add': 'Add',
    'portfolio.current_price': 'Current Price',
    'portfolio.avg_price': 'Avg Price',
    'portfolio.weighted_avg_price': 'Weighted average price',
    'portfolio.add_transaction': 'Add transaction',
    'portfolio.add_first_crypto': 'Add my first crypto',
    'portfolio.modify': 'Edit',
    'portfolio.delete': 'Delete',
    'portfolio.modify_transaction': 'Edit Transaction',
    'portfolio.delete_transaction_confirm': 'Delete this transaction?',
    'portfolio.delete_transaction': 'Delete this transaction',
    'portfolio.purchase_price': 'Purchase price ($)',
    'portfolio.add_position': 'Add position',
    'portfolio.modify_position': 'Edit position',
    'portfolio.search_crypto': 'Search crypto...',
    'portfolio.loading_price': 'Loading price...',
    'portfolio.avg_purchase_price': 'Average purchase price ($)',
    'portfolio.current_price_label': 'Current price:',
    'portfolio.add_exchange': 'Add Exchange',
    'portfolio.quantity': 'Quantity',
    'portfolio.value': 'Value',
    'portfolio.profit_loss': 'P&L',
    'portfolio.total_value': 'Total Value',
    'portfolio.total_invested': 'Total Invested',
    'portfolio.total_profit': 'Total Profit/Loss',
    'portfolio.best_performer': 'Best Performer',
    'portfolio.worst_performer': 'Worst Performer',
    'portfolio.crypto': 'Crypto',
    'portfolio.actions': 'Actions',
    'portfolio.empty_state': 'No crypto in your portfolio',
    'portfolio.empty_desc': 'Start by adding your first positions',
    'portfolio.refresh': 'Refresh prices',
    'portfolio.show_values': 'Show values',
    'portfolio.hide_values': 'Hide values',
    'portfolio.transaction_date': 'Date',
    'portfolio.transaction_type': 'Type',
    'portfolio.transaction_buy': 'Buy',
    'portfolio.transaction_sell': 'Sell',
    'portfolio.no_transactions': 'No transactions',
    'portfolio.view_transactions': 'View transactions',
    'portfolio.close': 'Close',
    'portfolio.save': 'Save',
    'portfolio.cancel': 'Cancel',

    // Charts Page
    'charts.title': 'Advanced Charts',
    'charts.subtitle': 'Analyze markets with professional tools',
    'charts.search_crypto': 'Search cryptocurrency',
    'charts.my_watchlists': 'My Watchlists',
    'charts.add_to_portfolio': 'Add to Portfolio',
    'charts.refresh': 'Refresh',
    'charts.fullscreen': 'Fullscreen',
    'charts.download': 'Download',
    'charts.crypto_info': 'Crypto Info',
    'charts.current_price': 'Current Price',
    'charts.change_24h': '24h Change',
    'charts.market_cap': 'Market Cap',
    'charts.volume_24h': '24h Volume',
    'charts.loading': 'Loading chart...',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr')

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'fr' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
